### ISSUE TITLE
ExtSlice not supported

### ISSUE THREAD

**Issue by Stafil0** [best-doctor/flake8-expression-complexity#1]
ExtSlice, like o[x:y,z]

```python
>>> compile('o[x:y,z]', '<string>', 'exec', PyCF_ONLY_AST).body[0].value.slice
<_ast.ExtSlice object at 0xb72a9f0c>
```

throws exception
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\__main__.py", line 4, in <module>
    cli.main()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\main\cli.py", line 18, in main
    app.run(argv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\main\application.py", line 393, in run
    self._run(argv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\main\application.py", line 381, in _run
    self.run_checks()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\main\application.py", line 300, in run_checks
    self.file_checker_manager.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\checker.py", line 331, in run
    self.run_serial()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\checker.py", line 315, in run_serial
    checker.run_checks()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\checker.py", line 598, in run_checks
    self.run_ast_checks()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\checker.py", line 502, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8_expression_complexity\checker.py", line 46, in run
    complexity = get_expression_complexity(expression)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8_expression_complexity\utils\complexity.py", line 15, in get_expression_complexity
    return max_with_default(get_expression_complexity(n) for n in info['subnodes']) + score_addon
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8_expression_complexity\utils\iterables.py", line 9, in max_with_default
    items = list(items)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8_expression_complexity\utils\complexity.py", line 15, in <genexpr>
    return max_with_default(get_expression_complexity(n) for n in info['subnodes']) + score_addon
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8_expression_complexity\utils\complexity.py", line 15, in get_expression_complexity
    return max_with_default(get_expression_complexity(n) for n in info['subnodes']) + score_addon
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8_expression_complexity\utils\iterables.py", line 9, in max_with_default
    items = list(items)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8_expression_complexity\utils\complexity.py", line 15, in <genexpr>
    return max_with_default(get_expression_complexity(n) for n in info['subnodes']) + score_addon
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8_expression_complexity\utils\complexity.py", line 11, in get_expression_complexity
    info = get_expression_part_info(node)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8_expression_complexity\utils\complexity.py", line 92, in get_expression_part_info
    raise AssertionError('should always get node type')
AssertionError: should always get node type
```

**Comment by Melevir** [comment]
Fixed. Please install `flake8-expression-complexity==0.0.3`
