### ISSUE TITLE
Support of match-case statements

### ISSUE THREAD

**Issue by krepysh** [best-doctor/flake8-expression-complexity#19]
**Is your feature request related to a problem? Please describe.**
At this point linter failed on match-case statements

**Describe the solution you'd like**
Success run when match-case in code

**Describe alternatives you've considered**
As alternative it is possible to ignore match-case statements

**Additional context**
Linter will failed on this code:
```
link = '<https://example.com/path/>; rel="next"'
match link.split('; '):
    case [brackets_link, 'rel="next"']:
        url = brackets_link[1:-1]
    case [brackets_link, 'rel="previous"']:
        url = brackets_link[1:-1]
```

With following error:
```
Match(
    lineno=2,
    col_offset=0,
    end_lineno=6,
    end_col_offset=33,
    subject=Call(
        lineno=2,
        col_offset=6,
        end_lineno=2,
        end_col_offset=22,
        func=Attribute(
            lineno=2,
            col_offset=6,
            end_lineno=2,
            end_col_offset=16,
            value=Name(lineno=2, col_offset=6, end_lineno=2, end_col_offset=10, id='link', ctx=Load()),
            attr='split',
            ctx=Load(),
        ),
        args=[Constant(lineno=2, col_offset=17, end_lineno=2, end_col_offset=21, value='; ', kind=None)],
        keywords=[],
    ),
    cases=[
        match_case(
            pattern=MatchSequence(
                lineno=3,
                col_offset=9,
                end_lineno=3,
                end_col_offset=38,
                patterns=[
                    MatchAs(lineno=3, col_offset=10, end_lineno=3, end_col_offset=23, pattern=None, name='brackets_link'),
                    MatchValue(
                        lineno=3,
                        col_offset=25,
                        end_lineno=3,
                        end_col_offset=37,
                        value=Constant(lineno=3, col_offset=25, end_lineno=3, end_col_offset=37, value='rel="next"', kind=None),
                    ),
                ],
            ),
            guard=None,
            body=[
                Assign(
                    lineno=4,
                    col_offset=8,
                    end_lineno=4,
                    end_col_offset=33,
                    targets=[Name(lineno=4, col_offset=8, end_lineno=4, end_col_offset=11, id='url', ctx=Store())],
                    value=Subscript(
                        lineno=4,
                        col_offset=14,
                        end_lineno=4,
                        end_col_offset=33,
                        value=Name(lineno=4, col_offset=14, end_lineno=4, end_col_offset=27, id='brackets_link', ctx=Load()),
                        slice=Slice(
                            lineno=4,
                            col_offset=28,
                            end_lineno=4,
                            end_col_offset=32,
                            lower=Constant(lineno=4, col_offset=28, end_lineno=4, end_col_offset=29, value=1, kind=None),
                            upper=UnaryOp(
                                lineno=4,
                                col_offset=30,
                                end_lineno=4,
                                end_col_offset=32,
                                op=USub(),
                                operand=Constant(lineno=4, col_offset=31, end_lineno=4, end_col_offset=32, value=1, kind=None),
                            ),
                            step=None,
                        ),
                        ctx=Load(),
                    ),
                    type_comment=None,
                ),
            ],
        ),
        match_case(
            pattern=MatchSequence(
                lineno=5,
                col_offset=9,
                end_lineno=5,
                end_col_offset=42,
                patterns=[
                    MatchAs(lineno=5, col_offset=10, end_lineno=5, end_col_offset=23, pattern=None, name='brackets_link'),
                    MatchValue(
                        lineno=5,
                        col_offset=25,
                        end_lineno=5,
                        end_col_offset=41,
                        value=Constant(lineno=5, col_offset=25, end_lineno=5, end_col_offset=41, value='rel="previous"', kind=None),
                    ),
                ],
            ),
            guard=None,
            body=[
                Assign(
                    lineno=6,
                    col_offset=8,
                    end_lineno=6,
                    end_col_offset=33,
                    targets=[Name(lineno=6, col_offset=8, end_lineno=6, end_col_offset=11, id='url', ctx=Store())],
                    value=Subscript(
                        lineno=6,
                        col_offset=14,
                        end_lineno=6,
                        end_col_offset=33,
                        value=Name(lineno=6, col_offset=14, end_lineno=6, end_col_offset=27, id='brackets_link', ctx=Load()),
                        slice=Slice(
                            lineno=6,
                            col_offset=28,
                            end_lineno=6,
                            end_col_offset=32,
                            lower=Constant(lineno=6, col_offset=28, end_lineno=6, end_col_offset=29, value=1, kind=None),
                            upper=UnaryOp(
                                lineno=6,
                                col_offset=30,
                                end_lineno=6,
                                end_col_offset=32,
                                op=USub(),
                                operand=Constant(lineno=6, col_offset=31, end_lineno=6, end_col_offset=32, value=1, kind=None),
                            ),
                            step=None,
                        ),
                        ctx=Load(),
                    ),
                    type_comment=None,
                ),
            ],
        ),
    ],
)
Traceback (most recent call last):
  File "/Users/at/.virtualenvs/zs/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/Users/re/.virtualenvs/zs/lib/python3.10/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/Users/re/.virtualenvs/zs/lib/python3.10/site-packages/flake8/main/application.py", line 375, in run
    self._run(argv)
  File "/Users/re/.virtualenvs/zs/lib/python3.10/site-packages/flake8/main/application.py", line 364, in _run
    self.run_checks()
  File "/Users/re/.virtualenvs/zs/lib/python3.10/site-packages/flake8/main/application.py", line 271, in run_checks
    self.file_checker_manager.run()
  File "/Users/re/.virtualenvs/zs/lib/python3.10/site-packages/flake8/checker.py", line 311, in run
    self.run_serial()
  File "/Users/re/.virtualenvs/zs/lib/python3.10/site-packages/flake8/checker.py", line 295, in run_serial
    checker.run_checks()
  File "/Users/re/.virtualenvs/zs/lib/python3.10/site-packages/flake8/checker.py", line 597, in run_checks
    self.run_ast_checks()
  File "/Users/re/.virtualenvs/zs/lib/python3.10/site-packages/flake8/checker.py", line 500, in run_ast_checks
    for (line_number, offset, text, _) in runner:
  File "/Users/re/.virtualenvs/zs/lib/python3.10/site-packages/flake8_expression_complexity/checker.py", line 46, in run
    complexity = get_expression_complexity(expression)
  File "/Users/re/.virtualenvs/zs/lib/python3.10/site-packages/flake8_expression_complexity/utils/complexity.py", line 58, in get_expression_complexity
    info = get_expression_part_info(node)
  File "/Users/re/.virtualenvs/zs/lib/python3.10/site-packages/flake8_expression_complexity/utils/complexity.py", line 104, in get_expression_part_info
    raise AssertionError('should always get node type')
AssertionError: should always get node type
```

**Comment by korneevm** [comment]
Thanks, @krepysh!

I've merged your pr and released a new version of the plugin https://pypi.org/project/flake8-expression-complexity/0.0.11/
