### ISSUE TITLE
Async funcs not supported

### ISSUE THREAD

**Issue by Stafil0** [best-doctor/flake8-expression-complexity#2]
Any async func, like
```python
async def some_async_func(a, b, c):
    result = await other_async_func(c, b, a)
    return result
```

throws
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda2\envs\flake\Scripts\flake8.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\main\cli.py", line 18, in main
    app.run(argv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\main\application.py", line 393, in run
    self._run(argv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\main\application.py", line 381, in _run
    self.run_checks()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\main\application.py", line 300, in run_checks
    self.file_checker_manager.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\checker.py", line 331, in run
    self.run_serial()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\checker.py", line 315, in run_serial
    checker.run_checks()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\checker.py", line 598, in run_checks
    self.run_ast_checks()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\checker.py", line 502, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8_expression_complexity\checker.py", line 46, in run
    complexity = get_expression_complexity(expression)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8_expression_complexity\utils\complexity.py", line 11, in get_expression_complexity
    info = get_expression_part_info(node)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8_expression_complexity\utils\complexity.py", line 94, in get_expression_part_info
    raise AssertionError('should always get node type')
AssertionError: should always get node type
```

AST node
```
AsyncFunctionDef(
    lineno=1,
    col_offset=6,
    name='some_async_func',
    args=arguments(
        args=[
            arg(lineno=1, col_offset=26, arg='a', annotation=None),
            arg(lineno=1, col_offset=29, arg='b', annotation=None),
            arg(lineno=1, col_offset=32, arg='c', annotation=None),
        ],
        vararg=None,
        kwonlyargs=[],
        kw_defaults=[],
        kwarg=None,
        defaults=[],
    ),
    body=[
        Assign(
            lineno=2,
            col_offset=4,
            targets=[Name(lineno=2, col_offset=4, id='result', ctx=Store())],
            value=Await(
                lineno=2,
                col_offset=13,
                value=Call(
                    lineno=2,
                    col_offset=19,
                    func=Name(lineno=2, col_offset=19, id='other_async_func', ctx=Load()),
                    args=[
                        Name(lineno=2, col_offset=36, id='c', ctx=Load()),
                        Name(lineno=2, col_offset=39, id='b', ctx=Load()),
                        Name(lineno=2, col_offset=42, id='a', ctx=Load()),
                    ],
                    keywords=[],
                ),
            ),
        ),
        Return(
            lineno=3,
            col_offset=4,
            value=Name(lineno=3, col_offset=11, id='result', ctx=Load()),
        ),
    ],
    decorator_list=[],
    returns=None,
)
```

**Comment by Melevir** [comment]
Fixed. Please, update to v0.0.4, it should work.
