### ISSUE TITLE
Lacks dependency on astpretty

### ISSUE THREAD

**Issue by languitar** [best-doctor/flake8-expression-complexity#5]
It seems the current release version in pypi of this project lacks a dependency on astpretty. After installation, flake8 fails with:
```
Traceback (most recent call last):
  File "/home/languitar/.pyenv/versions/3.7.4/envs/poetl/lib/python3.7/site-packages/flake8/plugins/manager.py", line 158, in load_plugin
    self._load()
  File "/home/languitar/.pyenv/versions/3.7.4/envs/poetl/lib/python3.7/site-packages/flake8/plugins/manager.py", line 135, in _load
    self._plugin = self.entry_point.load()
  File "/home/languitar/.pyenv/versions/3.7.4/envs/poetl/lib/python3.7/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/home/languitar/.pyenv/versions/3.7.4/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/languitar/.pyenv/versions/3.7.4/envs/poetl/lib/python3.7/site-packages/flake8_expression_complexity/checker.py", line 6, in <module>
    from flake8_expression_complexity.utils.complexity import get_expression_complexity
  File "/home/languitar/.pyenv/versions/3.7.4/envs/poetl/lib/python3.7/site-packages/flake8_expression_complexity/utils/complexity.py", line 5, in <module>
    from astpretty import pprint
ModuleNotFoundError: No module named 'astpretty'
```

Installing `astpretty` solves the issue.

**Comment by Melevir** [comment]
Fixed. Please, update to v0.0.5 of the plugin.
