### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by Dreamsorcerer** [best-doctor/flake8-expression-complexity#7]
Running flake8 after installing this extension results in the below error:

```
AsyncWith(
    lineno=35,
    col_offset=14,
    items=[
        withitem(
            context_expr=Call(
                lineno=35,
                col_offset=19,
                func=Attribute(
                    lineno=35,
                    col_offset=19,
                    value=Attribute(
                        lineno=35,
                        col_offset=19,
                        value=Name(lineno=35, col_offset=19, id='self', ctx=Load()),
                        attr='_session',
                        ctx=Load(),
                    ),
                    attr='post',
                    ctx=Load(),
                ),
                args=[Name(lineno=35, col_offset=38, id='TOKEN_URL', ctx=Load())],
                keywords=[
                    keyword(
                        arg='data',
                        value=Name(lineno=35, col_offset=54, id='request_data', ctx=Load()),
                    ),
                ],
            ),
            optional_vars=Name(lineno=35, col_offset=71, id='resp', ctx=Store()),
        ),
    ],
    body=[
        Assign(
            lineno=36,
            col_offset=12,
            targets=[Name(lineno=36, col_offset=12, id='response_json', ctx=Store())],
            value=Await(
                lineno=36,
                col_offset=28,
                value=Call(
                    lineno=36,
                    col_offset=34,
                    func=Attribute(
                        lineno=36,
                        col_offset=34,
                        value=Name(lineno=36, col_offset=34, id='resp', ctx=Load()),
                        attr='json',
                        ctx=Load(),
                    ),
                    args=[],
                    keywords=[],
                ),
            ),
        ),
        If(
            lineno=37,
            col_offset=12,
            test=Compare(
                lineno=37,
                col_offset=15,
                left=Attribute(
                    lineno=37,
                    col_offset=15,
                    value=Name(lineno=37, col_offset=15, id='resp', ctx=Load()),
                    attr='status',
                    ctx=Load(),
                ),
                ops=[Eq()],
                comparators=[Num(lineno=37, col_offset=30, n=401)],
            ),
            body=[
                Raise(
                    lineno=38,
                    col_offset=16,
                    exc=Call(
                        lineno=38,
                        col_offset=22,
                        func=Name(lineno=38, col_offset=22, id='AuthenticationError', ctx=Load()),
                        args=[Name(lineno=38, col_offset=42, id='response_json', ctx=Load())],
                        keywords=[],
                    ),
                    cause=None,
                ),
            ],
            orelse=[],
        ),
    ],
)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/checker.py", line 666, in _run_checks
    return checker.run_checks()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/checker.py", line 598, in run_checks
    self.run_ast_checks()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/checker.py", line 502, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8_expression_complexity/checker.py", line 46, in run
    complexity = get_expression_complexity(expression)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8_expression_complexity/utils/complexity.py", line 11, in get_expression_complexity
    info = get_expression_part_info(node)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8_expression_complexity/utils/complexity.py", line 96, in get_expression_part_info
    raise AssertionError('should always get node type')
AssertionError: should always get node type
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/main/application.py", line 393, in run
    self._run(argv)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/main/application.py", line 381, in _run
    self.run_checks()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/main/application.py", line 300, in run_checks
    self.file_checker_manager.run()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/checker.py", line 329, in run
    self.run_parallel()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/checker.py", line 293, in run_parallel
    for ret in pool_map:
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
AssertionError: should always get node type
```

**Comment by Dreamsorcerer** [comment]
```
> flake8 --bug-report
{
  "dependencies": [
    {
      "dependency": "entrypoints",
      "version": "0.3"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.6.8",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-darglint",
      "version": "0.4.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-expression-complexity",
      "version": "0.0.5"
    },
    {
      "is_local": false,
      "plugin": "flake8_coding",
      "version": "1.3.2"
    },
    {
      "is_local": false,
      "plugin": "flake8_implicit_str_concat",
      "version": "0.1.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_isort",
      "version": "2.3"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.5.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.1.1"
    },
    {
      "is_local": false,
      "plugin": "radon",
      "version": "4.0.0"
    },
    {
      "is_local": false,
      "plugin": "rst-docstrings",
      "version": "0.0.12"
    }
  ],
  "version": "3.7.9"
}
```

**Comment by Melevir** [comment]
Fixed. Please, update to version 0.0.6 of the plugin.
