### ISSUE TITLE
global not supported 

### ISSUE THREAD

**Issue by wushilong** [best-doctor/flake8-expression-complexity#8]
## 1. global not supported 
`global ` statement, like
```python
user = None
def foo():
    global user
```
throws
```
Global(lineno=25, col_offset=8, names=['user'])
Traceback (most recent call last):
  File "c:\users\codemonk\appdata\local\programs\python\python37\Lib\runpy.py", line 193, in _run_module_as_main                                                                                                    "__main__", mod_spec)
  File "c:\users\codemonk\appdata\local\programs\python\python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\codemonk\Desktop\project\.tox\flake8\Scripts\flake8.EXE\__main__.py", line 7, in <module>
  File "c:\users\codemonk\desktop\project\.tox\flake8\lib\site-packages\flake8\main\cli.py", line 18, in main
    app.run(argv)
  File "c:\users\codemonk\desktop\project\.tox\flake8\lib\site-packages\flake8\main\application.py", line 393, in run                                                                                               self._run(argv)
  File "c:\users\codemonk\desktop\project\.tox\flake8\lib\site-packages\flake8\main\application.py", line 381, in _run
    self.run_checks()
  File "c:\users\codemonk\desktop\project\.tox\flake8\lib\site-packages\flake8\main\application.py", line 300, in run_checks
    self.file_checker_manager.run()
  File "c:\users\codemonk\desktop\project\.tox\flake8\lib\site-packages\flake8\checker.py", line 331, in run
    self.run_serial()
  File "c:\users\codemonk\desktop\project\.tox\flake8\lib\site-packages\flake8\checker.py", line 315, in run_serial
    checker.run_checks()
  File "c:\users\codemonk\desktop\project\.tox\flake8\lib\site-packages\flake8\checker.py", line 598, in run_checks
    self.run_ast_checks()
  File "c:\users\codemonk\desktop\project\.tox\flake8\lib\site-packages\flake8\checker.py", line 502, in run_ast_checks    for (line_number, offset, text, check) in runner:
  File "c:\users\codemonk\desktop\project\.tox\flake8\lib\site-packages\flake8_expression_complexity\checker.py", line 46, in run
    complexity = get_expression_complexity(expression)
  File "c:\users\codemonk\desktop\project\.tox\flake8\lib\site-packages\flake8_expression_complexity\utils\complexity.py", line 11, in get_expression_complexity
    info = get_expression_part_info(node)
  File "c:\users\codemonk\desktop\project\.tox\flake8\lib\site-packages\flake8_expression_complexity\utils\complexity.py", line 96, in get_expression_part_info
    raise AssertionError('should always get node type')
AssertionError: should always get node type
```

## 2. fix
**Sorry, I can't create a PR to fix it because submitting codes to github is prohibited. :(** 
### 2.1 add `global` statement in [unittest](https://github.com/best-doctor/flake8-expression-complexity/blob/a47056e5d9b4ba188ea441b59aa0da17940197c8/tests/test_files/long_expressions.py#L26)
```python
async def foo():
    global user
``` 
!NOTICE: unittest is red currently!

### 2.2 add `global`  node score in [get_complexity_increase_for_node_type](https://github.com/best-doctor/flake8-expression-complexity/blob/a47056e5d9b4ba188ea441b59aa0da17940197c8/flake8_expression_complexity/utils/complexity.py#L18)
```python
    nodes_scores_map = {
        'unary_op': 1,
        'global': 0,
```
### 2.3 add `global` node part info in [get_expression_part_info](https://github.com/best-doctor/flake8-expression-complexity/blob/a47056e5d9b4ba188ea441b59aa0da17940197c8/flake8_expression_complexity/utils/complexity.py#L48)
```python
    types_map = [
        (ast.UnaryOp, 'unary_op'),
        (ast.Global, 'global'),
```
### 2.4 add `global` subnode map in [_get_sub_nodes](https://github.com/best-doctor/flake8-expression-complexity/blob/a47056e5d9b4ba188ea441b59aa0da17940197c8/flake8_expression_complexity/utils/complexity.py#L104)
```python
    subnodes_map = {
        'unary_op': lambda n: [n.operand],
        'global': lambda n: [],
```

unittest is green! :)

**Comment by Melevir** [comment]
Fixed. Pleasy, update to v0.0.7 of the plugin.
